In [6]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [7]:
train_images.shape

(60000, 28, 28)

In [8]:
len(train_labels)

60000

In [9]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [10]:
test_images.shape

(10000, 28, 28)

In [11]:
len(test_labels)

10000

In [12]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [13]:
from tensorflow import keras
from tensorflow.keras import layers
model = keras.Sequential([
    layers.Dense(512, activation="relu"),
    layers.Dense(10, activation="softmax")
])

In [14]:
model.compile(optimizer="rmsprop",
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])

In [15]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255

In [16]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

2024-01-31 09:12:45.364538: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2024-01-31 09:12:45.367770: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 3593205000 Hz


Epoch 1/5


2024-01-31 09:12:45.654717: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10


469/469 [==============================] - 1s 1ms/step - loss: 0.4246 - accuracy: 0.8801
Epoch 2/5
469/469 [==============================] - 1s 1ms/step - loss: 0.1089 - accuracy: 0.9671
Epoch 3/5
469/469 [==============================] - 1s 1ms/step - loss: 0.0673 - accuracy: 0.9792
Epoch 4/5
469/469 [==============================] - 1s 1ms/step - loss: 0.0480 - accuracy: 0.9854
Epoch 5/5
469/469 [==============================] - 1s 1ms/step - loss: 0.0357 - accuracy: 0.9891


In [17]:
test_digits = test_images[0:10]

In [18]:
predictions = model.predict(test_digits)

In [19]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 512)               401920    
_________________________________________________________________
dense_3 (Dense)              (None, 10)                5130      
Total params: 407,050
Trainable params: 407,050
Non-trainable params: 0
_________________________________________________________________


In [15]:
predictions[0]

array([3.9118021e-11, 2.6805107e-15, 2.7526548e-10, 1.1819208e-05,
       3.2875125e-16, 4.9768711e-10, 5.7593798e-18, 9.9998820e-01,
       3.5020156e-09, 4.4527503e-08], dtype=float32)

In [16]:
predictions[0].argmax()

7

In [17]:
predictions[0][7]

0.9999882

In [18]:
test_loss, test_acc = model.evaluate(test_images, test_labels)

313/313 [==============================] - 0s 839us/step - loss: 0.0749 - accuracy: 0.9806


In [19]:
print(f"test_acc: {test_acc}")

test_acc: 0.9805999994277954
