In [1]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

2024-01-30 22:46:53.758093: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1


In [2]:
train_images.shape

(60000, 28, 28)

In [3]:
len(train_labels)

60000

In [4]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [5]:
test_images.shape

(10000, 28, 28)

In [6]:
len(test_labels)

10000

In [7]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [8]:
from tensorflow import keras
from tensorflow.keras import layers
model = keras.Sequential([
    layers.Dense(512, activation="relu"),
    layers.Dense(10, activation="softmax")
])

2024-01-30 22:52:48.546147: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2024-01-30 22:52:48.547277: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2024-01-30 22:52:48.609521: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2024-01-30 22:52:48.609883: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:0a:00.0 name: NVIDIA GeForce RTX 2070 computeCapability: 7.5
coreClock: 1.62GHz coreCount: 36 deviceMemorySize: 7.78GiB deviceMemoryBandwidth: 417.29GiB/s
2024-01-30 22:52:48.609935: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node 

In [9]:
model.compile(optimizer="rmsprop",
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])

In [10]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255

In [12]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 1s 1ms/step - loss: 0.0287 - accuracy: 0.9912
Epoch 2/5
469/469 [==============================] - 1s 1ms/step - loss: 0.0222 - accuracy: 0.9936
Epoch 3/5
469/469 [==============================] - 1s 1ms/step - loss: 0.0174 - accuracy: 0.9948
Epoch 4/5
469/469 [==============================] - 1s 1ms/step - loss: 0.0130 - accuracy: 0.9963
Epoch 5/5
469/469 [==============================] - 1s 1ms/step - loss: 0.0105 - accuracy: 0.9971


In [13]:
test_digits = test_images[0:10]

In [14]:
predictions = model.predict(test_digits)

In [15]:
predictions[0]

array([3.9118021e-11, 2.6805107e-15, 2.7526548e-10, 1.1819208e-05,
       3.2875125e-16, 4.9768711e-10, 5.7593798e-18, 9.9998820e-01,
       3.5020156e-09, 4.4527503e-08], dtype=float32)

In [16]:
predictions[0].argmax()

7

In [17]:
predictions[0][7]

0.9999882

In [18]:
test_loss, test_acc = model.evaluate(test_images, test_labels)

313/313 [==============================] - 0s 839us/step - loss: 0.0749 - accuracy: 0.9806


In [19]:
print(f"test_acc: {test_acc}")

test_acc: 0.9805999994277954
